-- DROP DATABASE IF EXISTS `DB`;
-- CREATE DATABASE `DB`;
--
-- CREATE USER 'root'@'%' IDENTIFIED BY 'password';
-- GRANT ALL PRIVILEGES ON *.* TO 'root'@'%';
--
-- FLUSH PTIVILEGES;
--
-- USE `DB`;
DROP DATABASE IF EXISTS `DB`;
CREATE DATABASE `DB`;
USE `DB`;
